In [7]:
!pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.61.1-cp313-cp313-win_amd64.whl.metadata (116 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.23 in C:\Users\renat\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\renat\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (26.0)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-12.1.1-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\renat\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\renat\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 5.7 MB/s eta 0:00:02
   ------------ --------------------------- 2.6/8.1 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.1 MB 16.6 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 15.0 MB/s  0:00:00
Downloading contourpy-1.3.3-cp313-cp313-win_amd64.whl (226 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.61.1-cp313-cp313-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 55.3 MB/s  0:00:00
Downloading kiwisolver-1.4.9-cp313-cp313-win_amd64.whl (73 kB)
Downloading pillow-12.1.1-cp313-cp313-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------- ----------- 5.0/7.0 MB 31.4 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.0 MB 17.6 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 15.4 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------- ----------------- 4/7 [cycler]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 kiwisolver-1.4.9 matplotlib-3.10.8 pillow-12.1.1 pyparsing-3.3.2

# Carregando a base de dados

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
ibovespa = pd.read_csv(r"../data/raw/Dados Históricos - Ibovespa.csv", sep=',')
ibovespa.head()

         Data   Último  Abertura   Máxima   Mínima    Vol.    Var%
0  19.02.2026  188.534   186.020  188.687  185.928   9,24B   1,35%
1  18.02.2026  186.016   186.464  187.657  185.001   7,79B  -0,24%
2  13.02.2026  186.464   187.766  187.766  183.662  11,59B  -0,69%
3  12.02.2026  187.766   189.694  189.990  186.959  12,36B  -1,02%
4  11.02.2026  189.699   185.936  190.561  185.936  11,64B   2,03%

In [5]:
# Quais os tipos informações compõe o banco de dados (base original)
ibovespa.info()

<class 'pandas.DataFrame'>
RangeIndex: 534 entries, 0 to 533
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Data      534 non-null    str
 1   Último    534 non-null    float64
 2   Abertura  534 non-null    float64
 3   Máxima    534 non-null    float64
 4   Mínima    534 non-null    float64
 5   Vol.      534 non-null    str
 6   Var%      534 non-null    str
dtypes: float64(4), str(3)
memory usage: 29.3 KB

# EDA - Análise Exploratória de Dados

In [6]:
# renomeando as colunas
ibovespa.rename(columns={'Data': 'data', 'Abertura': 'abertura', 'Máxima': 'maxima', 'Mínima': 'minima', 'Último': 'fechamento', 'Vol.': 'volume', "Var%": "variacao_percentual"}, inplace=True)
ibovespa.head()

,data,fechamento,abertura,maxima,minima,volume,variacao_percentual
0,19.02.2026,188.534,186.020,188.687,185.928,"9,24B","1,35%"
1,18.02.2026,186.016,186.464,187.657,185.001,"7,79B","-0,24%"
2,13.02.2026,186.464,187.766,187.766,183.662,"11,59B","-0,69%"
3,12.02.2026,187.766,189.694,189.990,186.959,"12,36B","-1,02%"
4,11.02.2026,189.699,185.936,190.561,185.936,"11,64B","2,03%"

In [87]:
# Transformando a coluna Data de objeto para data
ibovespa["data"] = pd.to_datetime(ibovespa["data"])
print(ibovespa.head())

        data  fechamento  abertura   maxima   minima  volume
0 2026-02-19     188.534   186.020  188.687  185.928   9,24B  \
1 2026-02-18     186.016   186.464  187.657  185.001   7,79B
2 2026-02-13     186.464   187.766  187.766  183.662  11,59B
3 2026-02-12     187.766   189.694  189.990  186.959  12,36B
4 2026-02-11     189.699   185.936  190.561  185.936  11,64B

  variacao_percentual
0               1,35%
1              -0,24%
2              -0,69%
3              -1,02%
4               2,03%

/var/folders/x7/hy6kgv1x6_s5fx88qm5c36t40000gn/T/ipykernel_44543/1809113291.py:2: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ibovespa["data"] = pd.to_datetime(ibovespa["data"])

In [88]:
# Ajustando a coluna de variação
ibovespa["variacao_percentual"] = ibovespa["variacao_percentual"].str.replace('%', '').str.replace(',', '.').astype(float)
print(ibovespa.head())

        data  fechamento  abertura   maxima   minima  volume
0 2026-02-19     188.534   186.020  188.687  185.928   9,24B  \
1 2026-02-18     186.016   186.464  187.657  185.001   7,79B
2 2026-02-13     186.464   187.766  187.766  183.662  11,59B
3 2026-02-12     187.766   189.694  189.990  186.959  12,36B
4 2026-02-11     189.699   185.936  190.561  185.936  11,64B

   variacao_percentual
0                 1.35
1                -0.24
2                -0.69
3                -1.02
4                 2.03

In [89]:
# Quantidade de dados nulos por coluna
ibovespa.isnull().sum()

data                   0
fechamento             0
abertura               0
maxima                 0
minima                 0
volume                 0
variacao_percentual    0
dtype: int64

In [90]:
# Criando uma coluna se fechou em alta ou em baixa
ibovespa['status'] = ibovespa.apply(lambda row: 'alta' if row['variacao_percentual'] > 0 else 'baixa', axis=1)
ibovespa.head()

,data,fechamento,abertura,maxima,minima,volume,variacao_percentual,status
0,2026-02-19,188.534,186.020,188.687,185.928,"9,24B",1.35,alta
1,2026-02-18,186.016,186.464,187.657,185.001,"7,79B",-0.24,baixa
2,2026-02-13,186.464,187.766,187.766,183.662,"11,59B",-0.69,baixa
3,2026-02-12,187.766,189.694,189.990,186.959,"12,36B",-1.02,baixa
4,2026-02-11,189.699,185.936,190.561,185.936,"11,64B",2.03,alta

In [91]:
# Validando a saída final da base
ibovespa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534 entries, 0 to 533
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data                 534 non-null    datetime64[ns]
 1   fechamento           534 non-null    float64
 2   abertura             534 non-null    float64
 3   maxima               534 non-null    float64
 4   minima               534 non-null    float64
 5   volume               534 non-null    object
 6   variacao_percentual  534 non-null    float64
 7   status               534 non-null    object
dtypes: datetime64[ns](1), float64(5), object(2)
memory usage: 33.5+ KB

In [92]:
# Considerando apenas as colunas relevantes
ibovespa_final = ibovespa[['data', 'abertura', 'maxima', 'minima', 'fechamento', 'variacao_percentual', 'status']]

In [93]:
# Salvando dataframe final em csv
ibovespa_final.to_csv('../data/trusted/ibovespa_historico.csv', index=False, sep = ';')