# Carregando a base de dados

In [81]:
import pandas as pd

In [82]:
ibovespa = pd.read_csv(r"../data/raw/Dados Históricos - Ibovespa.csv", sep=',')
ibovespa.head()

         Data   Último  Abertura   Máxima   Mínima    Vol.    Var%
0  19.02.2026  188.534   186.020  188.687  185.928   9,24B   1,35%
1  18.02.2026  186.016   186.464  187.657  185.001   7,79B  -0,24%
2  13.02.2026  186.464   187.766  187.766  183.662  11,59B  -0,69%
3  12.02.2026  187.766   189.694  189.990  186.959  12,36B  -1,02%
4  11.02.2026  189.699   185.936  190.561  185.936  11,64B   2,03%

In [83]:
# Quais os tipos informações compõe o banco de dados (base original)
ibovespa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534 entries, 0 to 533
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Data      534 non-null    object
 1   Último    534 non-null    float64
 2   Abertura  534 non-null    float64
 3   Máxima    534 non-null    float64
 4   Mínima    534 non-null    float64
 5   Vol.      534 non-null    object
 6   Var%      534 non-null    object
dtypes: float64(4), object(3)
memory usage: 29.3+ KB

# EDA - Análise Exploratória de Dados IBOVESPA

In [84]:
# renomeando as colunas
ibovespa.rename(columns={'Data': 'data', 'Abertura': 'abertura', 'Máxima': 'maxima', 'Mínima': 'minima', 'Último': 'fechamento', 'Vol.': 'volume', "Var%": "variacao_percentual"}, inplace=True)
ibovespa.head()

,data,fechamento,abertura,maxima,minima,volume,variacao_percentual
0,19.02.2026,188.534,186.020,188.687,185.928,"9,24B","1,35%"
1,18.02.2026,186.016,186.464,187.657,185.001,"7,79B","-0,24%"
2,13.02.2026,186.464,187.766,187.766,183.662,"11,59B","-0,69%"
3,12.02.2026,187.766,189.694,189.990,186.959,"12,36B","-1,02%"
4,11.02.2026,189.699,185.936,190.561,185.936,"11,64B","2,03%"

In [85]:
# Transformando a coluna Data de objeto para data
ibovespa["data"] = pd.to_datetime(ibovespa["data"])
print(ibovespa.head())

        data  fechamento  abertura   maxima   minima  volume
0 2026-02-19     188.534   186.020  188.687  185.928   9,24B  \
1 2026-02-18     186.016   186.464  187.657  185.001   7,79B
2 2026-02-13     186.464   187.766  187.766  183.662  11,59B
3 2026-02-12     187.766   189.694  189.990  186.959  12,36B
4 2026-02-11     189.699   185.936  190.561  185.936  11,64B

  variacao_percentual
0               1,35%
1              -0,24%
2              -0,69%
3              -1,02%
4               2,03%

/var/folders/x7/hy6kgv1x6_s5fx88qm5c36t40000gn/T/ipykernel_15642/1809113291.py:2: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ibovespa["data"] = pd.to_datetime(ibovespa["data"])

In [86]:
# Ajustando a coluna de variação
ibovespa["variacao_percentual"] = ibovespa["variacao_percentual"].str.replace('%', '').str.replace(',', '.').astype(float)
print(ibovespa.head())

        data  fechamento  abertura   maxima   minima  volume
0 2026-02-19     188.534   186.020  188.687  185.928   9,24B  \
1 2026-02-18     186.016   186.464  187.657  185.001   7,79B
2 2026-02-13     186.464   187.766  187.766  183.662  11,59B
3 2026-02-12     187.766   189.694  189.990  186.959  12,36B
4 2026-02-11     189.699   185.936  190.561  185.936  11,64B

   variacao_percentual
0                 1.35
1                -0.24
2                -0.69
3                -1.02
4                 2.03

In [87]:
# Quantidade de dados nulos por coluna
ibovespa.isnull().sum()

data                   0
fechamento             0
abertura               0
maxima                 0
minima                 0
volume                 0
variacao_percentual    0
dtype: int64

In [88]:
# # Criando uma coluna se fechou em alta ou em baixa
# ibovespa['status'] = ibovespa.apply(lambda row: 'alta' if row['variacao_dia_posterior'] > 0 else 'baixa', axis=1)
# ibovespa.head()

In [89]:
def convert_volume(volume_str):
    if pd.isna(volume_str):
        return None
    
    volume_str = str(volume_str).strip()
    volume_str = volume_str.replace('.', '').replace(',', '.')
    
    if volume_str.endswith('M'):
        return float(volume_str[:-1]) * 1_000_000
    elif volume_str.endswith('B'):
        return float(volume_str[:-1]) * 1_000_000_000
    else:
        return float(volume_str)

ibovespa['vol_reais'] = ibovespa['volume'].apply(convert_volume)

In [90]:
# Validando a saída final da base
ibovespa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 534 entries, 0 to 533
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data                 534 non-null    datetime64[ns]
 1   fechamento           534 non-null    float64
 2   abertura             534 non-null    float64
 3   maxima               534 non-null    float64
 4   minima               534 non-null    float64
 5   volume               534 non-null    object
 6   variacao_percentual  534 non-null    float64
 7   vol_reais            534 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 33.5+ KB

# Enriquecendo com o dolar do dia

In [91]:
dolar = pd.read_csv(r"../data/raw/USD_BRL Dados Históricos.csv", sep=',')
dolar = dolar[['Data', 'Último']]
dolar.rename(columns={'Data': 'data', 'Último': 'cotacao_dia_dolar'}, inplace=True)
dolar['data'] = pd.to_datetime(dolar['data'])
dolar['cotacao_dia_dolar'] = dolar['cotacao_dia_dolar'].str.replace(',', '.').astype(float)
dolar.head()

/var/folders/x7/hy6kgv1x6_s5fx88qm5c36t40000gn/T/ipykernel_15642/2405383847.py:4: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  dolar['data'] = pd.to_datetime(dolar['data'])

        data  cotacao_dia_dolar
0 2026-02-23             5.1690
1 2026-02-22             5.1768
2 2026-02-20             5.1768
3 2026-02-19             5.2109
4 2026-02-18             5.2359

In [92]:
dolar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 562 entries, 0 to 561
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   data               562 non-null    datetime64[ns]
 1   cotacao_dia_dolar  562 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 8.9 KB

In [93]:
ibovespa_enriquecido = ibovespa.merge(dolar, on='data', how='left')

In [94]:
ibovespa_enriquecido.isnull().sum()

data                   0
fechamento             0
abertura               0
maxima                 0
minima                 0
volume                 0
variacao_percentual    0
vol_reais              0
cotacao_dia_dolar      0
dtype: int64

# Enriquecendo S&P 500

In [95]:
sep_500 = pd.read_csv(r"../data/raw/Dados Históricos - S&P 500.csv", sep=',')
sep_500 = sep_500[['Data', 'Último']]
sep_500.rename(columns={'Data': 'data', 'Último': 'cotacao_dia_sep_500'}, inplace=True)
sep_500['data'] = pd.to_datetime(sep_500['data'])
sep_500['cotacao_dia_sep_500'] = sep_500['cotacao_dia_sep_500'].str.replace('.', '').str.replace(',', '.').astype(float)
sep_500.head()

/var/folders/x7/hy6kgv1x6_s5fx88qm5c36t40000gn/T/ipykernel_15642/2872146975.py:4: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  sep_500['data'] = pd.to_datetime(sep_500['data'])

        data  cotacao_dia_sep_500
0 2026-02-19              6861.89
1 2026-02-18              6881.31
2 2026-02-17              6843.22
3 2026-02-13              6836.17
4 2026-02-12              6832.76

In [96]:
ibovespa_enriquecido_2 = ibovespa_enriquecido.merge(sep_500, on='data', how='left')

# Enriquecendo preço Petróleo

In [97]:
petroleo = pd.read_csv(r"../data/raw/Dados Históricos - Petróleo Brent Futuros.csv", sep=',')
petroleo = petroleo[['Data', 'Último']]
petroleo.rename(columns={'Data': 'data', 'Último': 'cotacao_petroleo'}, inplace=True)
petroleo['data'] = pd.to_datetime(petroleo['data'])
petroleo['cotacao_petroleo'] = petroleo['cotacao_petroleo'].str.replace('.', '').str.replace(',', '.').astype(float)
petroleo.head()

/var/folders/x7/hy6kgv1x6_s5fx88qm5c36t40000gn/T/ipykernel_15642/2307325895.py:4: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  petroleo['data'] = pd.to_datetime(petroleo['data'])

        data  cotacao_petroleo
0 2026-02-19             71.27
1 2026-02-18             69.77
2 2026-02-17             66.87
3 2026-02-16             67.97
4 2026-02-13             67.75

In [98]:
ibovespa_enriquecido_3 = ibovespa_enriquecido_2.merge(petroleo, on='data', how='left')

# Formatando base final

In [99]:
# Considerando apenas as colunas relevantes
ibovespa_final = ibovespa_enriquecido_3[['data', 'abertura', 'maxima', 'minima', 'fechamento', 'vol_reais', 'variacao_percentual', 'cotacao_dia_dolar', 'cotacao_dia_sep_500', 'cotacao_petroleo']]

In [100]:
# # Salvando dataframe final em csv
ibovespa_final.to_csv('../data/trusted/ibovespa_historico.csv', index=False, sep = ';')